### ISSUE TITLE
一点小补充

### ISSUE THREAD

**Issue by Rodelia-86** [gledos/ggame#7]
一份北京关于游戏审查的会议记录总结，我把它发在了我的频道上，https://t.me/ncbdjdjsbxhchdjsj/16

**Comment by gledos** [comment]
多谢，不过《网络游戏内容管理培训班开班动员讲话内容整理》已经收录了，链接是： https://ggame.gledos.science/research/网络游戏内容管理培训班开班动员讲话内容整理.html
